import { test, expect } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
})

test('Player 1 should win', async ({ page }) => {
  await expect(page.getByText('Player 1 Turn')).toBeVisible()
  await page.locator('.bg-white').first().click()
  await expect(page.getByText('Player 2 Turn')).toBeVisible()
  await page.locator('.bg-white').first().click()
  await page.locator('button:nth-child(5)').click()
  await page.locator('button:nth-child(6)').click()
  await page.locator('button:nth-child(9)').click()
  await page.locator('button:nth-child(10)').click()
  await page.locator('button:nth-child(13)').click()
  await expect(page.getByText('Player 1 Wins!')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Restart' })).toBeVisible()
})

test('Player 2 should win', async ({ page }) => {
  await expect(page.getByText('Player 1 Turn')).toBeVisible()
  await page.locator('button:nth-child(3)').click()
  await expect(page.getByText('Player 2 Turn')).toBeVisible()
  await page.locator('button:nth-child(6)').click()
  await page.locator('button:nth-child(7)').click()
  await page.locator('button:nth-child(11)').click()
  await page.locator('button:nth-child(2)').click()
  await page.locator('.bg-white').first().click()
  await page.locator('.bg-white').first().click()
  await page.locator('button:nth-child(16)').click()
  await expect(page.getByText('Player 2 Wins!')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Restart' })).toBeVisible()
})

test('Game should end in a draw', async ({ page }) => {
  await expect(page.getByText('Player 1 Turn')).toBeVisible()
  await page.locator('button:nth-child(3)').click()
  await expect(page.getByText('Player 2 Turn')).toBeVisible()
  await page.locator('button:nth-child(2)').click()
  await page.locator('button:nth-child(6)').click()
  await page.locator('button:nth-child(7)').click()
  await page.locator('button:nth-child(8)').click()
  await page.locator('button:nth-child(10)').click()
  await page.locator('button:nth-child(5)').click()
  await page.locator('button:nth-child(9)').click()
  await page.locator('button:nth-child(14)').click()
  await page.locator('button:nth-child(11)').click()
  await page.locator('button:nth-child(12)').click()
  await page.locator('button:nth-child(15)').click()
  await page.locator('button:nth-child(16)').click()
  await page.locator('button:nth-child(4)').click()
  await page.locator('button:nth-child(13)').click()
  await page.locator('.bg-white').click()
  await expect(page.getByText('Game is a Draw!')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Restart' })).toBeVisible()
})
